disabled = false
languageCode = "es"
languageName = "Spanish"
weight = 2
title = "Blog de Mora"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Este es mi blog de tecnología, donde documento mis peleas con nuevas herramientas, comparto descubrimientos e intento no ahogarme en este mar llamado tecnología."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Gael Mora"
   email = "m0r4a@proton.me"
   image = "author.jpg"
   imageQuality = 96
   headline = "Linux, programación y creación de servidores confiables."
   bio = "Sample bio"
   links = [
     { email = "mailto:m0r4a@proton.me" },
#     { link = "https://link-to-some-website.com/" },
#     { discord = "https://discord.gg/invitecode" },
#     { facebook = "https://facebook.com/username" },
     { github = "https://github.com/m0r4a" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
     { linkedin = "https://linkedin.com/in/m0r4a" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
